# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c7720de1391da38f5ce5c454f576255"
name = "LikeProducts"
application_url = "https://3b1fe8f5d353.ngrok-free.app"
embedded = true
handle = "likeproducts"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products,read_products,read_customers"

[auth]
redirect_urls = [
  "https://3b1fe8f5d353.ngrok-free.app/auth/callback",
  "https://3b1fe8f5d353.ngrok-free.app/auth/shopify/callback",
  "https://3b1fe8f5d353.ngrok-free.app/api/auth/callback"
]


[app_proxy]
prefix = "apps"
subpath = "wishlist"
url = "https://3b1fe8f5d353.ngrok-free.app/api/wishlist"
