# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c7720de1391da38f5ce5c454f576255"
name = "LikeProducts"
application_url = "https://d3d0e242983a.ngrok-free.app"
embedded = true
handle = "likeproducts"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://bc9966a615a7.ngrok-free.app/auth/callback", "https://bc9966a615a7.ngrok-free.app/auth/shopify/callback", "https://bc9966a615a7.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
